version: '3.3'
services:
  crypto3:
    build:
      context: ./Docker
    image: pctf22_crypto3:latest
    restart: always
    privileged: true
    entrypoint: /bin/bash
    command: /home/ctf/startup.sh
    ports:
      - "3002:3000"

networks:
  default:
    name: pctf22_crypto3
    driver: bridge
